trigger:
  - master
  - develop
  - homolog

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    buildtag: 'prd'
    environmentName: 'PRD_VM_ECOMMIT'

  ${{ if eq(variables['Build.SourceBranchName'], 'homolog') }}:
    buildtag: 'hmg'
    environmentName: 'HMG_VM_ECOMMIT'

  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    buildtag: 'dev'
    environmentName: 'DEV_VM_ECOMMIT'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Compile_and_distribution
    jobs:
      - job: Compile
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean install --settings="settings.xml"'
              publishJUnitResults: false
              jdkVersionOption: '1.11'
              javaHomeOption: 'JDKVersion'
              mavenOptions: '-Xmx3072m'

          - task: Docker@2
            inputs:
              containerRegistry: 'ICRSAAS'
              repository: 'dpsstorageapi'
              command: 'build'
              tags: $(buildtag)
              Dockerfile: '**/Dockerfile'

          - task: Docker@2
            inputs:
              containerRegistry: 'ICRSAAS'
              repository: 'dpsstorageapi'
              command: 'push'
              tags: $(buildtag)

  - stage: Deploy
    jobs:
      - deployment: VMDeploy
        displayName: dpsstorageapi
        pool:
          vmImage: 'Ubuntu-latest'
        environment:
          name: $(environmentName)
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - script: docker pull icrsaas.azurecr.io/dpsstorageapi:$(buildtag)
                - script: docker-compose -f /var/docker/docker-compose.yml up -d

